# -*- coding: utf-8 -*-
"""EjerciciosTasas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWS6FCT0QEiSS56Bm9tA6nSgtawNeYtk
"""

#Tasa periodica=Tasa Nominal/#periodos al año

def nominal_a_efectiva_anual(tasa_nominal_anual, periodos_cap):
    return (1 + tasa_nominal_anual / periodos_cap) ** periodos_cap - 1

#Mensual= 12, trimestral = 4 semestral =2

def nominal_a_efectiva_anual_trimestral(tasa_nominal_anual):
    return nominal_a_efectiva_anual(tasa_nominal_anual, 4)

def efectiva_anual_a_nominal_mensual(tasa_efectiva_anual):
    return 12 * ( (1 + tasa_efectiva_anual) ** (1/12) - 1 )

def efectiva_semestral_a_anual(tasa_efectiva_semestral):
    return (1 + tasa_efectiva_semestral) ** 2 - 1

def efectiva_anual_a_semestral(tasa_efectiva_anual):
    return (1 + tasa_efectiva_anual) ** (1/2) - 1


tasa_nominal_anual = 0.34  # 34%
tasa_efectiva_anual_equivalente = nominal_a_efectiva_anual(tasa_nominal_anual, 12)
print(f"Tasa efectiva anual equivalente: {tasa_efectiva_anual_equivalente:.4f}")

# Cálculo con tasa nominal del 36% y capitalización trimestral
tasa_nominal_anual_36 = 0.36
tasa_efectiva_anual_36 = nominal_a_efectiva_anual_trimestral(tasa_nominal_anual_36)
print(f"Tasa efectiva anual equivalente: {tasa_efectiva_anual_36:.4f}")

# Cálculo de tasa nominal mensual desde efectiva anual 41.16%
tasa_efectiva_anual_41_16 = 0.4116
tasa_nominal_mensual = efectiva_anual_a_nominal_mensual(tasa_efectiva_anual_41_16)
print(f"Tasa nominal mensual: {tasa_nominal_mensual:.4f}")

# Cálculo de tasa efectiva anual desde semestral 12%
tasa_efectiva_semestral_12 = 0.12
tasa_efectiva_anual = efectiva_semestral_a_anual(tasa_efectiva_semestral_12)
print(f"Tasa efectiva anual: {tasa_efectiva_anual:.4f}")

# Cálculo de tasa semestral desde efectiva anual 12%
tasa_efectiva_anual_12 = 0.12
tasa_efectiva_semestral = efectiva_anual_a_semestral(tasa_efectiva_anual_12)
print(f"Tasa efectiva semestral: {tasa_efectiva_semestral:.4f}")